var listOfGames = [
    {
        id: 200,
        name: "Cyberpunk",
        img: <img src="../images/games/img_game_cyberpunk.jpg"></img>,
        description: "Cyberpunk is an open-world, action-adventure story set in Night City, a megalopolis obsessed with power, glamour and body modification. You play as V, a mercenary outlaw going after a one-of-a-kind implant that is the key to immortality. You can customize your character’s cyberware, skillset and play style, and explore a vast city where the choices you make shape the story and the world around you.",
        age: "16",
        type: "Playbox One X",
        resolution: "4K Ultra HD",
        state: "new",
        price: "$ 19.99",
    },

    {
        id: 201,
        name: "Space War",
        img: <img src="../images/games/img_game_spacewar.jpg"></img>,
        description: "Space War is a space combat video game where you explore and fight your way thorugh different galaxies. Customize your spacecraft with different materials and weapons etc.",
        age: "16",
        type: "Playbox One X",
        resolution: "4K Ultra HD",
        state: "new",
        price: "$ 19.99",
    },

    {
        id: 202,
        name: "Ping Pong Championship",
        img: <img src="../images/games/img_game_pingpong.jpg"></img>,
        description: "Challenge your friends and family in an epic game of ping pong with Ping Pong Championship. You can also challenge and play with friends online.",
        age: "3+",
        type: "Playbox One X",
        resolution: "4K Ultra HD",
        state: "new",
        price: "$ 14.99",
    },

    {
        id: 203,
        name: "Black",
        img: <img src="../images/games/img_game_black.jpg"></img>,
        description: "Black is a straightforward first-person shooter, mission-based game. The player takes control of Jack Kellar, a black ops agent who is being questioned about his previous mission involving a terrorist operation.",
        age: "16",
        type: "Playbox One X",
        resolution: "4K Ultra HD",
        state: "new",
        price: "$ 19.99",
    },

    {
        id: 204,
        name: "Assassin",
        img: <img src="../images/games/img_game_assassin.jpg"></img>,
        description: "Assassin is a live-action game in which players try to eliminate one another using mock weapons, in an effort to become the last surviving player.",
        age: "16",
        type: "Playbox One X",
        resolution: "4K Ultra HD",
        state: "new",
        price: "$ 19.99",
    },

    {
        id: 205,
        name: "Furious",
        img: <img src="../images/games/img_game_furious.jpg"></img>,
        description: "In this game you play as the gorilla, Furious, rampaging through the city.",
        age: "16",
        type: "Playbox One X",
        resolution: "4K Ultra HD",
        state: "new",
        price: "$ 29.99",
    },

    {
        id: 206,
        name: "Super Duper",
        img: <img src="../images/games/img_game_superduper.jpg"></img>,
        description: "Super Duper is a game for all ages. Jump, play and imitate the moves Super Duper shows you.",
        age: "3+",
        type: "Playbox One X",
        resolution: "4K Ultra HD",
        state: "used",
        price: "$ 9.99",
    },

    {
        id: 207,
        name: "Forge Legend",
        img: <img src="../images/games/img_game_forgelegend.jpg"></img>,
        description: "Forge Legend is a massively multiplayer online role-playing game. The game allows players to create a character avatar and explore an open game world in third- or first-person view, exploring the landscape, fighting various monsters, completing quests, and interacting with non-player characters (NPCs) or other players. The game encourages players to work together to complete quests, enter dungeons and engage in player versus player (PvP) combat, however, the game can also be played solo without interacting with others. The game primarily focuses on character progression, in which players earn experience points to level up their character to make them more powerful and buy and sell items using in-game currency to acquire better equipment, among other game systems.",
        age: "16",
        type: "Playbox One X",
        resolution: "4K Ultra HD",
        state: "used",
        price: "$ 11.99",
    },

    {
        id: 208,
        name: "Racing",
        img: <img src="../images/games/img_game_racing.jpg"></img>,
        description: "Rise to glory in Career mode, race against the world in Duels, or test your nerve in special events.",
        age: "16",
        type: "Playbox One X",
        resolution: "4K Ultra HD",
        state: "used",
        price: "$ 9.99",
    },

];